from __future__ import annotations

from ...knowledge_graph.definition import GraphDefinition
from .ministry_graph import (
    MINISTRY_ALIASES,
    MINISTRY_DATASET_JOINS,
    MINISTRY_DATASET_LINKS,
    MINISTRY_DATASETS,
    MINISTRY_ENTITIES,
    MINISTRY_METRICS,
    MINISTRY_RELATIONSHIPS,
)


_KERALA_DISTRICT_NODES = (
    ("ThiruvananthapuramDistrict", "Thiruvananthapuram"),
    ("KollamDistrict", "Kollam"),
    ("PathanamthittaDistrict", "Pathanamthitta"),
    ("AlappuzhaDistrict", "Alappuzha"),
    ("KottayamDistrict", "Kottayam"),
    ("IdukkiDistrict", "Idukki"),
    ("ErnakulamDistrict", "Ernakulam"),
    ("ThrissurDistrict", "Thrissur"),
    ("PalakkadDistrict", "Palakkad"),
    ("MalappuramDistrict", "Malappuram"),
    ("KozhikodeDistrict", "Kozhikode"),
    ("WayanadDistrict", "Wayanad"),
    ("KannurDistrict", "Kannur"),
    ("KasaragodDistrict", "Kasaragod"),
)

_DISTRICT_PYRAMID_LEVELS = (
    ("DistrictGeneralHospital", "Typically 1; medium-district example 1; serves the entire district."),
    ("TalukTHQH", "Typically 3-8; medium-district example 4-7; approximately one per taluk."),
    ("CHCBlockFHC", "Typically 5-15; medium-district example 6-12; approximately one per block or service cluster."),
    ("PHCFHC", "Typically 30-60; medium-district example 30-50; approximately one per panchayat or 30,000 people."),
    ("SubCentreJAK", "Typically hundreds; medium-district example 150-300; serves villages and wards."),
)


GRAPH_DEFINITION = GraphDefinition(
    ministry="health",
    registry_version="health-ministry-analytics-2026-07-23.1",
    entities=(
        {"name": "FiscalYear", "description": "Government fiscal reporting period."},
        {"name": "Equipment", "description": "Medical equipment asset assigned to a hospital."},
        {"name": "Syndrome", "description": "Governed clinical syndrome category used for aggregate early-warning surveillance."},
        {"name": "SurveillanceSignal", "description": "Deterministic daily anomaly signal requiring human verification; it is not an outbreak declaration."},
        {"name": "HealthcareFacilityLevel", "description": "Governed classification in Kerala's public healthcare referral hierarchy."},
        {"name": "SubCentreJAK", "description": "Sub Centre / Janakeeya Arogya Kendram: vaccinations, antenatal care, basic services, and health education."},
        {"name": "PHCFHC", "description": "Primary/Family Health Centre: first doctor contact, common illnesses, chronic disease management, and minor procedures."},
        {"name": "CHCBlockFHC", "description": "Community Health Centre / Block FHC: basic specialist care, inpatient beds, and emergency stabilization."},
        {"name": "TalukTHQH", "description": "Taluk/THQ Hospital: broader specialist, surgical, labor-room, diagnostic, blood-storage, and selected ICU services."},
        {"name": "DistrictGeneralHospital", "description": "District/General Hospital: full secondary multi-specialty care, major surgery, ICU, dialysis, and trauma services."},
        {"name": "MedicalCollegeHospital", "description": "Medical College Hospital: tertiary care, advanced surgery, teaching, research, and cross-district referrals."},
        {"name": "SuperSpecialtyInstitute", "description": "Disease-specific institute such as RCC or SCTIMST; specialty-referral-only rather than a general public escalation destination."},
        *(
            {
                "name": node_name,
                "description": f"Kerala administrative district: {display_name}.",
            }
            for node_name, display_name in _KERALA_DISTRICT_NODES
        ),
        *MINISTRY_ENTITIES,
    ),
    datasets=(
        {
            "name": "analytics_health_hospital_funding_year",
            "description": "Reviewed operating funding analytical view.",
            "grain": "Hospital x FiscalYear x FundingCategory",
            "governed": True,
            "fields": (
                {"column_name": "hospital_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable hospital key.", "ordinal": 1},
                {"column_name": "master_facility_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Reconciled common facility key; null while a compatibility identity remains unmapped.", "ordinal": 2},
                {"column_name": "hospital_name", "semantic_role": "label", "data_type": "text", "description": "Hospital display name.", "ordinal": 3},
                {"column_name": "district_name", "semantic_role": "dimension", "data_type": "text", "description": "District under administrative attribution.", "ordinal": 4},
                {"column_name": "fiscal_year", "semantic_role": "time", "data_type": "integer", "description": "Fiscal year start year.", "ordinal": 5},
                {"column_name": "funding_category", "semantic_role": "dimension", "data_type": "text", "description": "Funding category.", "ordinal": 6},
                {"column_name": "operating_funding", "semantic_role": "measure", "data_type": "real", "description": "Operating funding in lakh rupees.", "ordinal": 7},
                {"column_name": "source_version", "semantic_role": "provenance", "data_type": "text", "description": "Source dataset version.", "ordinal": 8},
            ),
        },
        *MINISTRY_DATASETS,
        {
            "name": "analytics_health_hospital_output_year",
            "description": "Reviewed hospital service output analytical view.",
            "grain": "Hospital x FiscalYear",
            "governed": True,
            "fields": (
                {"column_name": "hospital_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable hospital key.", "ordinal": 1},
                {"column_name": "master_facility_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Reconciled common facility key; null while a compatibility identity remains unmapped.", "ordinal": 2},
                {"column_name": "hospital_name", "semantic_role": "label", "data_type": "text", "description": "Hospital display name.", "ordinal": 3},
                {"column_name": "district_name", "semantic_role": "dimension", "data_type": "text", "description": "District under administrative attribution.", "ordinal": 4},
                {"column_name": "fiscal_year", "semantic_role": "time", "data_type": "integer", "description": "Fiscal year start year.", "ordinal": 5},
                {"column_name": "admissions", "semantic_role": "measure", "data_type": "integer", "description": "Annual admissions.", "ordinal": 6},
                {"column_name": "outpatient_visits", "semantic_role": "measure", "data_type": "integer", "description": "Annual outpatient visits.", "ordinal": 7},
                {"column_name": "surgeries", "semantic_role": "measure", "data_type": "integer", "description": "Annual surgeries.", "ordinal": 8},
                {"column_name": "source_version", "semantic_role": "provenance", "data_type": "text", "description": "Source dataset version.", "ordinal": 9},
            ),
        },
        {
            "name": "analytics_health_hospital_equipment",
            "description": "Governed hospital medical-equipment inventory and operational status view.",
            "grain": "Equipment asset",
            "governed": True,
            "fields": (
                {"column_name": "equipment_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable equipment asset key.", "ordinal": 1},
                {"column_name": "hospital_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Hospital responsible for the equipment.", "ordinal": 2},
                {"column_name": "master_facility_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Reconciled common facility key; null while a compatibility identity remains unmapped.", "ordinal": 3},
                {"column_name": "hospital_name", "semantic_role": "label", "data_type": "text", "description": "Hospital display name.", "ordinal": 4},
                {"column_name": "district_name", "semantic_role": "dimension", "data_type": "text", "description": "Hospital administrative district.", "ordinal": 5},
                {"column_name": "equipment_type", "semantic_role": "dimension", "data_type": "text", "description": "Medical equipment category.", "ordinal": 6},
                {"column_name": "asset_code", "semantic_role": "identifier", "data_type": "text", "description": "Unique equipment asset code.", "ordinal": 7},
                {"column_name": "operational_status", "semantic_role": "status", "data_type": "text", "description": "Operational, maintenance, or out-of-service state.", "ordinal": 8},
                {"column_name": "commissioned_on", "semantic_role": "time", "data_type": "text", "description": "Date the asset entered service.", "ordinal": 9},
                {"column_name": "last_maintenance_on", "semantic_role": "time", "data_type": "text", "description": "Most recent recorded maintenance date.", "ordinal": 10},
                {"column_name": "downtime_hours_last_12m", "semantic_role": "measure", "data_type": "real", "description": "Recorded downtime hours during the previous 12 months.", "ordinal": 11},
                {"column_name": "source_version", "semantic_role": "provenance", "data_type": "text", "description": "Source dataset version.", "ordinal": 12},
            ),
        },
        {
            "name": "analytics_health_hospital_care_level",
            "description": "Current effective-dated care-level classification for each hospital.",
            "grain": "Hospital",
            "governed": True,
            "fields": (
                {"column_name": "hospital_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable hospital key.", "ordinal": 1},
                {"column_name": "master_facility_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Reconciled common facility key; null while a compatibility identity remains unmapped.", "ordinal": 2},
                {"column_name": "hospital_name", "semantic_role": "label", "data_type": "text", "description": "Hospital display name.", "ordinal": 3},
                {"column_name": "district_name", "semantic_role": "dimension", "data_type": "text", "description": "Hospital administrative district.", "ordinal": 4},
                {"column_name": "level_code", "semantic_role": "classification", "data_type": "text", "description": "Stable care-level code.", "ordinal": 5},
                {"column_name": "care_level_name", "semantic_role": "label", "data_type": "text", "description": "Care-level display name.", "ordinal": 6},
                {"column_name": "hierarchy_order", "semantic_role": "ordinal", "data_type": "integer", "description": "Position in the referral hierarchy.", "ordinal": 7},
                {"column_name": "main_role", "semantic_role": "description", "data_type": "text", "description": "Primary services delivered at this level.", "ordinal": 8},
                {"column_name": "public_access_mode", "semantic_role": "policy", "data_type": "text", "description": "Direct, referral/emergency, or specialty-referral-only access.", "ordinal": 9},
                {"column_name": "disease_specific", "semantic_role": "policy", "data_type": "integer", "description": "Whether access depends on a matching disease specialty.", "ordinal": 10},
                {"column_name": "effective_from", "semantic_role": "time", "data_type": "text", "description": "Classification validity start.", "ordinal": 11},
                {"column_name": "effective_to", "semantic_role": "time", "data_type": "text", "description": "Classification validity end, null when current.", "ordinal": 12},
                {"column_name": "source_version", "semantic_role": "provenance", "data_type": "text", "description": "Source dataset version.", "ordinal": 13},
            ),
        },
        {
            "name": "analytics_health_facility_referral_route",
            "description": "Ordered Kerala public healthcare referral routes and access qualifications.",
            "grain": "From care level x to care level x route type",
            "governed": True,
            "fields": (
                {"column_name": "from_hierarchy_order", "semantic_role": "ordinal", "data_type": "integer", "description": "Origin position in the hierarchy.", "ordinal": 1},
                {"column_name": "from_level_code", "semantic_role": "classification", "data_type": "text", "description": "Origin care-level code.", "ordinal": 2},
                {"column_name": "from_level_name", "semantic_role": "label", "data_type": "text", "description": "Origin care-level name.", "ordinal": 3},
                {"column_name": "from_main_role", "semantic_role": "description", "data_type": "text", "description": "Origin level's primary role.", "ordinal": 4},
                {"column_name": "from_public_access_mode", "semantic_role": "policy", "data_type": "text", "description": "Origin access mode.", "ordinal": 5},
                {"column_name": "to_hierarchy_order", "semantic_role": "ordinal", "data_type": "integer", "description": "Destination position in the hierarchy.", "ordinal": 6},
                {"column_name": "to_level_code", "semantic_role": "classification", "data_type": "text", "description": "Destination care-level code.", "ordinal": 7},
                {"column_name": "to_level_name", "semantic_role": "label", "data_type": "text", "description": "Destination care-level name.", "ordinal": 8},
                {"column_name": "to_main_role", "semantic_role": "description", "data_type": "text", "description": "Destination level's primary role.", "ordinal": 9},
                {"column_name": "to_public_access_mode", "semantic_role": "policy", "data_type": "text", "description": "Destination access mode.", "ordinal": 10},
                {"column_name": "to_disease_specific", "semantic_role": "policy", "data_type": "integer", "description": "Whether the destination requires a matching disease specialty.", "ordinal": 11},
                {"column_name": "route_type", "semantic_role": "relationship_type", "data_type": "text", "description": "Severity escalation or disease-specific referral.", "ordinal": 12},
                {"column_name": "referral_rule", "semantic_role": "policy", "data_type": "text", "description": "Qualification for moving to the destination level.", "ordinal": 13},
            ),
        },
        {
            "name": "analytics_health_district_referral_pyramid",
            "description": "Approximate typical-medium-district facility distribution profile for all 14 Kerala districts.",
            "grain": "District x care level x profile type",
            "governed": True,
            "fields": (
                {"column_name": "district_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable district key.", "ordinal": 1},
                {"column_name": "district_name", "semantic_role": "label", "data_type": "text", "description": "Kerala district name.", "ordinal": 2},
                {"column_name": "level_code", "semantic_role": "classification", "data_type": "text", "description": "Stable care-level code.", "ordinal": 3},
                {"column_name": "care_level_name", "semantic_role": "label", "data_type": "text", "description": "Care-level display name.", "ordinal": 4},
                {"column_name": "hierarchy_order", "semantic_role": "ordinal", "data_type": "integer", "description": "Position in the referral hierarchy.", "ordinal": 5},
                {"column_name": "main_role", "semantic_role": "description", "data_type": "text", "description": "Primary services delivered at this level.", "ordinal": 6},
                {"column_name": "typical_min_count", "semantic_role": "planning_range", "data_type": "integer", "description": "Typical lower count when numerically specified.", "ordinal": 7},
                {"column_name": "typical_max_count", "semantic_role": "planning_range", "data_type": "integer", "description": "Typical upper count when numerically specified.", "ordinal": 8},
                {"column_name": "typical_count_label", "semantic_role": "planning_range", "data_type": "text", "description": "Qualitative typical count when no numeric range was supplied.", "ordinal": 9},
                {"column_name": "example_min_count", "semantic_role": "planning_range", "data_type": "integer", "description": "Medium-district example lower count.", "ordinal": 10},
                {"column_name": "example_max_count", "semantic_role": "planning_range", "data_type": "integer", "description": "Medium-district example upper count.", "ordinal": 11},
                {"column_name": "population_served", "semantic_role": "coverage_basis", "data_type": "text", "description": "Approximate population or administrative coverage basis.", "ordinal": 12},
                {"column_name": "public_access_mode", "semantic_role": "policy", "data_type": "text", "description": "Direct or referral/emergency access mode.", "ordinal": 13},
                {"column_name": "profile_type", "semantic_role": "method", "data_type": "text", "description": "Planning profile identifier.", "ordinal": 14},
                {"column_name": "is_approximate", "semantic_role": "assurance", "data_type": "integer", "description": "Always true for this supplied typical profile.", "ordinal": 15},
                {"column_name": "source_version", "semantic_role": "provenance", "data_type": "text", "description": "Profile source version.", "ordinal": 16},
            ),
        },
        {
            "name": "analytics_health_admission_daily",
            "description": "Governed aggregate daily hospital admissions by patient residence, syndrome, and age band.",
            "grain": "Hospital x patient district x reporting date x syndrome x age band",
            "governed": True,
            "fields": (
                {"column_name": "hospital_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable reporting hospital key.", "ordinal": 1},
                {"column_name": "master_facility_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Reconciled common facility key; null while a compatibility identity remains unmapped.", "ordinal": 2},
                {"column_name": "hospital_name", "semantic_role": "label", "data_type": "text", "description": "Reporting hospital name.", "ordinal": 3},
                {"column_name": "hospital_district_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Administrative district of the hospital.", "ordinal": 4},
                {"column_name": "hospital_district_name", "semantic_role": "dimension", "data_type": "text", "description": "Administrative district of the hospital.", "ordinal": 5},
                {"column_name": "patient_district_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Patient residence district used for geographic surveillance.", "ordinal": 6},
                {"column_name": "patient_district_name", "semantic_role": "dimension", "data_type": "text", "description": "Patient residence district used for geographic surveillance.", "ordinal": 7},
                {"column_name": "reporting_date", "semantic_role": "time", "data_type": "text", "description": "Closed daily reporting date.", "ordinal": 8},
                {"column_name": "syndrome_code", "semantic_role": "classification", "data_type": "text", "description": "Governed syndrome code.", "ordinal": 9},
                {"column_name": "syndrome_name", "semantic_role": "label", "data_type": "text", "description": "Governed syndrome name.", "ordinal": 10},
                {"column_name": "age_band", "semantic_role": "dimension", "data_type": "text", "description": "Non-identifying age band.", "ordinal": 11},
                {"column_name": "admissions", "semantic_role": "measure", "data_type": "integer", "description": "Aggregate daily admission count.", "ordinal": 12},
                {"column_name": "submission_status", "semantic_role": "status", "data_type": "text", "description": "Complete, partial, or missing daily submission state.", "ordinal": 13},
                {"column_name": "submitted_at", "semantic_role": "time", "data_type": "text", "description": "Submission timestamp.", "ordinal": 14},
                {"column_name": "source_version", "semantic_role": "provenance", "data_type": "text", "description": "Source dataset version.", "ordinal": 15},
            ),
        },
        {
            "name": "analytics_health_surveillance_signal",
            "description": "Daily deterministic admission anomalies awaiting human verification; rows are signals, not outbreak declarations.",
            "grain": "Surveillance run x geography x syndrome",
            "governed": True,
            "fields": (
                {"column_name": "signal_id", "semantic_role": "entity_key", "data_type": "integer", "description": "Stable signal identifier.", "ordinal": 1},
                {"column_name": "reporting_date", "semantic_role": "time", "data_type": "text", "description": "Closed reporting date evaluated.", "ordinal": 2},
                {"column_name": "geography_type", "semantic_role": "classification", "data_type": "text", "description": "Hospital, district, or state scope.", "ordinal": 3},
                {"column_name": "geography_id", "semantic_role": "foreign_key", "data_type": "integer", "description": "Identifier within the declared geography type.", "ordinal": 4},
                {"column_name": "geography_name", "semantic_role": "dimension", "data_type": "text", "description": "Human-readable geography.", "ordinal": 5},
                {"column_name": "syndrome_code", "semantic_role": "classification", "data_type": "text", "description": "Governed syndrome code.", "ordinal": 6},
                {"column_name": "syndrome_name", "semantic_role": "label", "data_type": "text", "description": "Governed syndrome name.", "ordinal": 7},
                {"column_name": "observed_count", "semantic_role": "measure", "data_type": "integer", "description": "Observed admissions.", "ordinal": 8},
                {"column_name": "expected_count", "semantic_role": "measure", "data_type": "real", "description": "Same-weekday baseline mean.", "ordinal": 9},
                {"column_name": "baseline_stddev", "semantic_role": "measure", "data_type": "real", "description": "Population standard deviation of baseline counts.", "ordinal": 10},
                {"column_name": "anomaly_score", "semantic_role": "measure", "data_type": "real", "description": "Standardized positive deviation used by the registered method.", "ordinal": 11},
                {"column_name": "observed_expected_ratio", "semantic_role": "measure", "data_type": "real", "description": "Observed-to-expected ratio when the expected count is positive.", "ordinal": 12},
                {"column_name": "contributing_hospitals", "semantic_role": "measure", "data_type": "integer", "description": "Distinct hospitals contributing current admissions.", "ordinal": 13},
                {"column_name": "reporting_completeness", "semantic_role": "assurance", "data_type": "real", "description": "Fraction of active hospitals with complete submissions.", "ordinal": 14},
                {"column_name": "corroborated", "semantic_role": "assurance", "data_type": "integer", "description": "Whether the multi-hospital corroboration rule passed.", "ordinal": 15},
                {"column_name": "signal_level", "semantic_role": "status", "data_type": "text", "description": "WATCH or HIGH triage level.", "ordinal": 16},
                {"column_name": "review_status", "semantic_role": "status", "data_type": "text", "description": "Human verification workflow state.", "ordinal": 17},
                {"column_name": "method_version", "semantic_role": "method", "data_type": "text", "description": "Registered deterministic detector version.", "ordinal": 18},
                {"column_name": "created_at", "semantic_role": "provenance", "data_type": "text", "description": "Signal creation timestamp.", "ordinal": 19},
            ),
        },
    ),
    metrics=(
        {"name": "operating_funding", "dataset_name": "analytics_health_hospital_funding_year", "expression": "SUM(operating_funding)", "aggregation": "sum", "unit": "lakh_inr", "additivity": "additive_by_hospital_and_fiscal_year", "entity_key": "hospital_id", "time_field": "fiscal_year", "valid_transforms": "none,endpoint_change,endpoint_growth_pct,endpoint_ratio", "zero_policy": "growth_requires_positive_start;ratio_requires_nonzero_start", "description": "Operating funding in lakh rupees."},
        {"name": "total_output", "dataset_name": "analytics_health_hospital_output_year", "expression": "SUM(admissions + outpatient_visits + surgeries)", "aggregation": "sum", "unit": "activity_count", "additivity": "additive_by_hospital_and_fiscal_year", "entity_key": "hospital_id", "time_field": "fiscal_year", "valid_transforms": "none,endpoint_change,endpoint_growth_pct,endpoint_ratio", "zero_policy": "growth_requires_positive_start;ratio_requires_nonzero_start", "description": "Composite activity count for this pilot; components remain visible."},
        {"name": "admissions", "dataset_name": "analytics_health_hospital_output_year", "expression": "SUM(admissions)", "aggregation": "sum", "unit": "activity_count", "additivity": "additive_by_hospital_and_fiscal_year", "entity_key": "hospital_id", "time_field": "fiscal_year", "valid_transforms": "none,endpoint_change,endpoint_growth_pct,endpoint_ratio", "zero_policy": "growth_requires_positive_start;ratio_requires_nonzero_start", "description": "Hospital inpatient admissions."},
        {"name": "outpatient_visits", "dataset_name": "analytics_health_hospital_output_year", "expression": "SUM(outpatient_visits)", "aggregation": "sum", "unit": "activity_count", "additivity": "additive_by_hospital_and_fiscal_year", "entity_key": "hospital_id", "time_field": "fiscal_year", "valid_transforms": "none,endpoint_change,endpoint_growth_pct,endpoint_ratio", "zero_policy": "growth_requires_positive_start;ratio_requires_nonzero_start", "description": "Hospital outpatient visits."},
        {"name": "surgeries", "dataset_name": "analytics_health_hospital_output_year", "expression": "SUM(surgeries)", "aggregation": "sum", "unit": "activity_count", "additivity": "additive_by_hospital_and_fiscal_year", "entity_key": "hospital_id", "time_field": "fiscal_year", "valid_transforms": "none,endpoint_change,endpoint_growth_pct,endpoint_ratio", "zero_policy": "growth_requires_positive_start;ratio_requires_nonzero_start", "description": "Hospital surgeries."},
        {"name": "hospital_count", "dataset_name": "analytics_health_hospital_funding_year", "expression": "COUNT(DISTINCT hospital_id)", "aggregation": "count_distinct", "unit": "hospital_count", "additivity": "non_additive_across_overlapping_groups", "entity_key": "hospital_id", "time_field": "fiscal_year", "valid_transforms": "none", "description": "Distinct hospital count."},
        {"name": "equipment_inventory", "dataset_name": "analytics_health_hospital_equipment", "expression": "equipment_id", "aggregation": "none", "description": "Hospital equipment asset inventory with current operational status."},
        {"name": "equipment_downtime", "dataset_name": "analytics_health_hospital_equipment", "expression": "SUM(downtime_hours_last_12m)", "aggregation": "sum", "unit": "hours", "additivity": "additive_by_equipment_asset", "entity_key": "equipment_id", "valid_transforms": "none", "description": "Equipment downtime hours recorded during the previous 12 months."},
        {"name": "care_level_inventory", "dataset_name": "analytics_health_hospital_care_level", "expression": "care_level_name", "aggregation": "none", "description": "Current effective-dated healthcare level assigned to each hospital."},
        {"name": "referral_hierarchy", "dataset_name": "analytics_health_facility_referral_route", "expression": "from_level_code -> to_level_code", "aggregation": "none", "description": "Ordered severity escalation ending in a qualified disease-specific super-specialty referral."},
        {"name": "district_referral_pyramid", "dataset_name": "analytics_health_district_referral_pyramid", "expression": "district_name x care_level_name x approximate_count_range", "aggregation": "none", "description": "Approximate five-level district referral-pyramid distribution profile."},
        {"name": "daily_admissions", "dataset_name": "analytics_health_admission_daily", "expression": "SUM(admissions)", "aggregation": "sum", "unit": "admission_count", "additivity": "additive_by_hospital_patient_district_syndrome_age_band_and_date", "entity_key": "hospital_id", "time_field": "reporting_date", "valid_transforms": "none", "description": "Aggregate daily syndrome-related hospital admissions."},
        {"name": "surveillance_signal_inventory", "dataset_name": "analytics_health_surveillance_signal", "expression": "signal_id", "aggregation": "none", "description": "Deterministic daily anomaly signals awaiting human verification; not outbreak declarations."},
        *MINISTRY_METRICS,
    ),
    relationships=(
        {"from_entity": "Hospital", "predicate": "located_in", "to_entity": "District", "join_expression": "hospital.district_id = district.district_id", "description": "Administrative location, not service catchment."},
        {"from_entity": "Hospital", "predicate": "has_funding_in", "to_entity": "FiscalYear", "join_expression": "hospital_funding.hospital_id = hospital.hospital_id", "description": "Observed funding by fiscal year."},
        {"from_entity": "Hospital", "predicate": "reports_output_in", "to_entity": "FiscalYear", "join_expression": "hospital_output.hospital_id = hospital.hospital_id", "description": "Observed service activity by fiscal year."},
        {"from_entity": "Hospital", "predicate": "has_equipment", "to_entity": "Equipment", "join_expression": "hospital_equipment.hospital_id = hospital.hospital_id", "description": "Hospital responsibility for a registered medical-equipment asset."},
        {"from_entity": "Hospital", "predicate": "classified_as", "to_entity": "HealthcareFacilityLevel", "join_expression": "hospital_facility_classification.hospital_id = hospital.hospital_id", "description": "Effective-dated care-level classification for a hospital."},
        {"from_entity": "Hospital", "predicate": "reports_daily_admissions_for", "to_entity": "Syndrome", "join_expression": "hospital_admission_daily.hospital_id = hospital.hospital_id", "description": "Aggregate daily syndrome admissions reported by a hospital."},
        {"from_entity": "SurveillanceSignal", "predicate": "flags_unusual_activity_for", "to_entity": "Syndrome", "join_expression": "health_surveillance_signal.syndrome_code = syndrome_category.syndrome_code", "description": "A deterministic anomaly requiring human verification, not an outbreak declaration."},
        {"from_entity": "SubCentreJAK", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = SUBCENTRE_JAK", "description": "Level 1 in the governed care hierarchy."},
        {"from_entity": "PHCFHC", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = PHC_FHC", "description": "Level 2 in the governed care hierarchy."},
        {"from_entity": "CHCBlockFHC", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = CHC_BLOCK_FHC", "description": "Level 3 in the governed care hierarchy."},
        {"from_entity": "TalukTHQH", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = TALUK_THQH", "description": "Level 4 in the governed care hierarchy."},
        {"from_entity": "DistrictGeneralHospital", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = DH_GH", "description": "Level 5 in the governed care hierarchy."},
        {"from_entity": "MedicalCollegeHospital", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = MCH", "description": "Level 6 in the governed care hierarchy."},
        {"from_entity": "SuperSpecialtyInstitute", "predicate": "is_a", "to_entity": "HealthcareFacilityLevel", "join_expression": "level_code = SUPER_SPECIALTY", "description": "Level 7 is disease-specific and specialty-referral-only."},
        {"from_entity": "SubCentreJAK", "predicate": "refers_to", "to_entity": "PHCFHC", "join_expression": "SUBCENTRE_JAK -> PHC_FHC", "description": "Escalate when basic services are insufficient or doctor assessment is required."},
        {"from_entity": "PHCFHC", "predicate": "refers_to", "to_entity": "CHCBlockFHC", "join_expression": "PHC_FHC -> CHC_BLOCK_FHC", "description": "Escalate for specialist assessment, inpatient care, or emergency stabilization."},
        {"from_entity": "CHCBlockFHC", "predicate": "refers_to", "to_entity": "TalukTHQH", "join_expression": "CHC_BLOCK_FHC -> TALUK_THQH", "description": "Escalate for broader specialist, surgical, diagnostic, or critical-care capability."},
        {"from_entity": "TalukTHQH", "predicate": "refers_to", "to_entity": "DistrictGeneralHospital", "join_expression": "TALUK_THQH -> DH_GH", "description": "Escalate for full secondary multi-specialty, major surgery, dialysis, or trauma capability."},
        {"from_entity": "DistrictGeneralHospital", "predicate": "refers_to", "to_entity": "MedicalCollegeHospital", "join_expression": "DH_GH -> MCH", "description": "Escalate complex tertiary, advanced surgical, teaching-hospital, or cross-district referral cases."},
        {"from_entity": "MedicalCollegeHospital", "predicate": "disease_specific_referral_to", "to_entity": "SuperSpecialtyInstitute", "join_expression": "MCH -> SUPER_SPECIALTY", "description": "Refer only for an illness matching the institute specialty; not a general public escalation route."},
        *(
            {
                "from_entity": district_node,
                "predicate": "is_a",
                "to_entity": "District",
                "join_expression": f"district_name = {district_name}",
                "description": f"{district_name} is one of Kerala's 14 administrative districts.",
            }
            for district_node, district_name in _KERALA_DISTRICT_NODES
        ),
        *(
            {
                "from_entity": district_node,
                "predicate": "typically_contains",
                "to_entity": level_entity,
                "join_expression": "district_facility_distribution_profile.district_id = district.district_id",
                "description": f"Approximate planning assumption for {district_name}: {description}",
            }
            for district_node, district_name in _KERALA_DISTRICT_NODES
            for level_entity, description in _DISTRICT_PYRAMID_LEVELS
        ),
        *MINISTRY_RELATIONSHIPS,
    ),
    aliases=(
        {"term": "hospital", "target_type": "entity", "target_name": "Hospital"},
        {"term": "hospitals", "target_type": "entity", "target_name": "Hospital"},
        {"term": "district", "target_type": "entity", "target_name": "District"},
        {"term": "funding", "target_type": "metric", "target_name": "operating_funding"},
        {"term": "fund", "target_type": "metric", "target_name": "operating_funding"},
        {"term": "spend", "target_type": "metric", "target_name": "operating_funding"},
        {"term": "output", "target_type": "metric", "target_name": "total_output"},
        {"term": "admission", "target_type": "metric", "target_name": "admissions"},
        {"term": "admissions", "target_type": "metric", "target_name": "admissions"},
        {"term": "daily admissions", "target_type": "metric", "target_name": "daily_admissions"},
        {"term": "admission spike", "target_type": "metric", "target_name": "surveillance_signal_inventory"},
        {"term": "outbreak signal", "target_type": "metric", "target_name": "surveillance_signal_inventory"},
        {"term": "surveillance signal", "target_type": "metric", "target_name": "surveillance_signal_inventory"},
        {"term": "syndrome", "target_type": "entity", "target_name": "Syndrome"},
        {"term": "signal", "target_type": "entity", "target_name": "SurveillanceSignal"},
        {"term": "surgery", "target_type": "metric", "target_name": "surgeries"},
        {"term": "surgeries", "target_type": "metric", "target_name": "surgeries"},
        {"term": "outpatient", "target_type": "metric", "target_name": "outpatient_visits"},
        {"term": "outpatient visits", "target_type": "metric", "target_name": "outpatient_visits"},
        {"term": "equipment", "target_type": "entity", "target_name": "Equipment"},
        {"term": "equipment", "target_type": "metric", "target_name": "equipment_inventory"},
        {"term": "asset", "target_type": "metric", "target_name": "equipment_inventory"},
        {"term": "assets", "target_type": "metric", "target_name": "equipment_inventory"},
        {"term": "machine", "target_type": "metric", "target_name": "equipment_inventory"},
        {"term": "machines", "target_type": "metric", "target_name": "equipment_inventory"},
        {"term": "downtime", "target_type": "metric", "target_name": "equipment_downtime"},
        {"term": "hierarchy", "target_type": "metric", "target_name": "referral_hierarchy"},
        {"term": "referral", "target_type": "metric", "target_name": "referral_hierarchy"},
        {"term": "severity", "target_type": "metric", "target_name": "referral_hierarchy"},
        {"term": "level", "target_type": "metric", "target_name": "care_level_inventory"},
        {"term": "levels", "target_type": "metric", "target_name": "care_level_inventory"},
        {"term": "jak", "target_type": "entity", "target_name": "SubCentreJAK"},
        {"term": "phc", "target_type": "entity", "target_name": "PHCFHC"},
        {"term": "fhc", "target_type": "entity", "target_name": "PHCFHC"},
        {"term": "chc", "target_type": "entity", "target_name": "CHCBlockFHC"},
        {"term": "thqh", "target_type": "entity", "target_name": "TalukTHQH"},
        {"term": "dh", "target_type": "entity", "target_name": "DistrictGeneralHospital"},
        {"term": "gh", "target_type": "entity", "target_name": "DistrictGeneralHospital"},
        {"term": "mch", "target_type": "entity", "target_name": "MedicalCollegeHospital"},
        {"term": "super-specialty", "target_type": "entity", "target_name": "SuperSpecialtyInstitute"},
        {"term": "specialty", "target_type": "entity", "target_name": "SuperSpecialtyInstitute"},
        {"term": "institute", "target_type": "entity", "target_name": "SuperSpecialtyInstitute"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "SubCentreJAK"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "PHCFHC"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "CHCBlockFHC"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "TalukTHQH"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "DistrictGeneralHospital"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "MedicalCollegeHospital"},
        {"term": "hierarchy", "target_type": "entity", "target_name": "SuperSpecialtyInstitute"},
        {"term": "distribution", "target_type": "metric", "target_name": "district_referral_pyramid"},
        {"term": "pyramid", "target_type": "metric", "target_name": "district_referral_pyramid"},
        *(
            {
                "term": term,
                "target_type": "entity",
                "target_name": district_node,
            }
            for term in ("distribution", "pyramid")
            for district_node, _ in _KERALA_DISTRICT_NODES
        ),
        *(
            {
                "term": district_name.lower(),
                "target_type": "entity",
                "target_name": district_node,
            }
            for district_node, district_name in _KERALA_DISTRICT_NODES
        ),
        *MINISTRY_ALIASES,
    ),
    dataset_links=(
        {"dataset_name": "analytics_health_hospital_funding_year", "entity_name": "Hospital", "metric_name": "operating_funding"},
        {"dataset_name": "analytics_health_hospital_funding_year", "entity_name": "Hospital", "metric_name": "hospital_count"},
        {"dataset_name": "analytics_health_hospital_output_year", "entity_name": "Hospital", "metric_name": "total_output"},
        {"dataset_name": "analytics_health_hospital_output_year", "entity_name": "Hospital", "metric_name": "admissions"},
        {"dataset_name": "analytics_health_hospital_output_year", "entity_name": "Hospital", "metric_name": "outpatient_visits"},
        {"dataset_name": "analytics_health_hospital_output_year", "entity_name": "Hospital", "metric_name": "surgeries"},
        {"dataset_name": "analytics_health_hospital_equipment", "entity_name": "Hospital", "metric_name": "equipment_inventory"},
        {"dataset_name": "analytics_health_hospital_equipment", "entity_name": "Equipment", "metric_name": "equipment_downtime"},
        {"dataset_name": "analytics_health_hospital_care_level", "entity_name": "Hospital", "metric_name": "care_level_inventory"},
        {"dataset_name": "analytics_health_facility_referral_route", "entity_name": "HealthcareFacilityLevel", "metric_name": "referral_hierarchy"},
        {"dataset_name": "analytics_health_district_referral_pyramid", "entity_name": "District", "metric_name": "district_referral_pyramid"},
        {"dataset_name": "analytics_health_admission_daily", "entity_name": "Hospital", "metric_name": "daily_admissions"},
        {"dataset_name": "analytics_health_admission_daily", "entity_name": "Syndrome", "metric_name": "daily_admissions"},
        {"dataset_name": "analytics_health_surveillance_signal", "entity_name": "SurveillanceSignal", "metric_name": "surveillance_signal_inventory"},
        {"dataset_name": "analytics_health_surveillance_signal", "entity_name": "Syndrome", "metric_name": "surveillance_signal_inventory"},
        *MINISTRY_DATASET_LINKS,
    ),
    dataset_joins=(
        {
            "left_dataset": "analytics_health_hospital_funding_year",
            "right_dataset": "analytics_health_hospital_output_year",
            "keys": (("hospital_id", "hospital_id"), ("fiscal_year", "fiscal_year")),
            "cardinality": "one_to_one_at_hospital_year_after_governed_view_filters",
            "description": "Join reviewed operating funding and service output at Hospital x FiscalYear grain.",
        },
        *MINISTRY_DATASET_JOINS,
    ),
)
