"""Peripheral K-Graph metadata for the ministry analytics redesign.

The graph intentionally stores organisational meaning, approved analytical
datasets, metrics, and relationships. Monthly measurements remain relational.
"""

from __future__ import annotations

from typing import Iterable


def _fields(rows: Iterable[tuple[str, str, str, str]]) -> tuple[dict[str, object], ...]:
    return tuple(
        {
            "column_name": name,
            "semantic_role": role,
            "data_type": data_type,
            "description": description,
            "ordinal": ordinal,
        }
        for ordinal, (name, role, data_type, description) in enumerate(rows, start=1)
    )


def _dataset(
    name: str,
    description: str,
    grain: str,
    rows: Iterable[tuple[str, str, str, str]],
) -> dict[str, object]:
    return {
        "name": name,
        "description": description,
        "grain": grain,
        "governed": True,
        "fields": _fields(rows),
    }


MINISTRY_ENTITIES = (
    {"name": "Department", "description": "Top-level Kerala health or AYUSH administrative department."},
    {"name": "Directorate", "description": "Directorate responsible for a defined health-service or education mandate."},
    {"name": "Organisation", "description": "Directorate, mission, corporation, regulator, autonomous institution, or district office."},
    {"name": "GeographicArea", "description": "Effective-dated state, district, taluk, block, local-body, ward, or catchment geography."},
    {"name": "LocalBody", "description": "Local self-government body participating in facility location, funding, or accountability."},
    {"name": "Facility", "description": "Common identity for modern-medicine, AYUSH, teaching, and specialty health facilities."},
    {"name": "FacilityType", "description": "Governed facility type and level classification."},
    {"name": "SystemOfMedicine", "description": "Modern Medicine, Ayurveda, Homoeopathy, Siddha, Unani, Yoga, Naturopathy, or Mixed."},
    {"name": "ServiceCategory", "description": "Broad governed service-delivery category."},
    {"name": "StaffCategory", "description": "Broad governed workforce category."},
    {"name": "EquipmentCategory", "description": "Broad governed medical-equipment category with criticality."},
    {"name": "InfrastructureCategory", "description": "Supporting infrastructure on which facility services depend."},
    {"name": "CostCategory", "description": "Governed expenditure classification."},
    {"name": "Programme", "description": "Public-health programme administered by an organisation."},
    {"name": "Scheme", "description": "Welfare or insurance scheme administered by an organisation."},
    {"name": "BudgetHead", "description": "Government budget classification and fund source."},
    {"name": "Supplier", "description": "Supplier or contractor serving a health organisation."},
    {"name": "ProcurementCategory", "description": "Broad governed procurement category."},
    {"name": "Project", "description": "Capital or digital-health project improving a facility or service."},
    {"name": "QualityIndicator", "description": "Governed quality, safety, compliance, or citizen-experience indicator."},
    {"name": "DemographicGroup", "description": "Aggregate equity dimension; never a person node."},
    {"name": "SourceSystem", "description": "Operational source system with an owner, steward, and refresh contract."},
    {"name": "AnalyticalMetric", "description": "Approved versioned metric definition."},
    {"name": "AnalyticalCapability", "description": "Safe reusable analysis with approved inputs, joins, privacy, and quality requirements."},
)


MINISTRY_DATASETS = (
    _dataset(
        "analytics_health_facility_monthly",
        "Executive facility-month resource, activity, finance, and access summary with centrally derived rates.",
        "Facility x Month",
        (
            ("facility_id", "entity_key", "integer", "Stable facility key."),
            ("facility_code", "identifier", "text", "Stable facility code."),
            ("facility_name", "label", "text", "Facility display name."),
            ("facility_type_name", "dimension", "text", "Facility type."),
            ("district_name", "dimension", "text", "Administrative district."),
            ("month_id", "time", "text", "First day of the reporting month."),
            ("outpatient_visits", "measure", "integer", "Monthly outpatient visits."),
            ("inpatient_admissions", "measure", "integer", "Monthly inpatient admissions."),
            ("emergency_visits", "measure", "integer", "Monthly emergency visits."),
            ("surgeries_completed", "measure", "integer", "Monthly completed surgeries."),
            ("deliveries_completed", "measure", "integer", "Monthly completed deliveries."),
            ("diagnostic_tests_completed", "measure", "integer", "Monthly diagnostic tests."),
            ("operational_beds", "measure", "integer", "Operational beds."),
            ("occupied_bed_days", "measure", "integer", "Occupied bed-days."),
            ("available_bed_days", "measure", "integer", "Available bed-days."),
            ("bed_occupancy_percentage", "measure", "real", "Occupied bed-days divided by available bed-days."),
            ("total_staff_required", "measure", "integer", "Required staff across categories."),
            ("total_staff_available", "measure", "integer", "Actually available staff across categories."),
            ("staff_sufficiency_percentage", "measure", "real", "Available staff divided by required staff."),
            ("total_budget_available", "measure", "real", "Available budget in rupees."),
            ("total_expenditure", "measure", "real", "Actual expenditure in rupees."),
            ("budget_utilisation_percentage", "measure", "real", "Expenditure divided by available budget."),
            ("average_waiting_minutes", "measure", "real", "Average waiting time in minutes."),
            ("patient_grievance_count", "measure", "integer", "Grievances received."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_medicine_monthly",
        "Facility-month medicine sufficiency, loss, stockout, delay, and emergency-purchase view.",
        "Facility x Month",
        (
            ("facility_id", "entity_key", "integer", "Stable facility key."),
            ("facility_name", "label", "text", "Facility display name."),
            ("district_name", "dimension", "text", "Administrative district."),
            ("month_id", "time", "text", "Reporting month."),
            ("available_stock_value", "measure", "real", "Available medicine stock value."),
            ("estimated_required_stock_value", "measure", "real", "Estimated required stock value."),
            ("medicine_sufficiency_percentage", "measure", "real", "Available divided by required stock value."),
            ("medicine_consumed_value", "measure", "real", "Medicine consumed value."),
            ("expired_medicine_value", "measure", "real", "Expired medicine value."),
            ("expiry_loss_percentage", "measure", "real", "Expired value divided by received value."),
            ("stockout_days", "measure", "integer", "Days with a stockout."),
            ("critical_stockout_incidents", "measure", "integer", "Critical stockout incidents."),
            ("average_supply_delay_days", "measure", "real", "Average supply delay in days."),
            ("emergency_local_purchase_cost", "measure", "real", "Emergency local purchase cost."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_equipment_monthly",
        "Facility-equipment-category-month sufficiency, functionality, downtime, and maintenance view.",
        "Facility x EquipmentCategory x Month",
        (
            ("facility_id", "entity_key", "integer", "Stable facility key."),
            ("facility_name", "label", "text", "Facility display name."),
            ("district_name", "dimension", "text", "Administrative district."),
            ("equipment_category", "dimension", "text", "Equipment category."),
            ("criticality", "classification", "text", "Routine, important, or critical."),
            ("month_id", "time", "text", "Reporting month."),
            ("equipment_required_count", "measure", "integer", "Required equipment count."),
            ("equipment_available_count", "measure", "integer", "Available equipment count."),
            ("equipment_functional_count", "measure", "integer", "Functional equipment count."),
            ("equipment_sufficiency_percentage", "measure", "real", "Available divided by required count."),
            ("equipment_functionality_percentage", "measure", "real", "Functional divided by available count."),
            ("total_downtime_hours", "measure", "real", "Total monthly downtime hours."),
            ("equipment_maintenance_cost", "measure", "real", "Maintenance cost in rupees."),
            ("maintenance_cost_ratio_percentage", "measure", "real", "Maintenance cost divided by procurement value."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_staffing_monthly",
        "Facility-staff-category-month required, sanctioned, filled, available, and cost view.",
        "Facility x StaffCategory x Month",
        (
            ("facility_id", "entity_key", "integer", "Stable facility key."),
            ("facility_name", "label", "text", "Facility display name."),
            ("district_name", "dimension", "text", "Administrative district."),
            ("staff_category", "dimension", "text", "Staff category."),
            ("month_id", "time", "text", "Reporting month."),
            ("required_posts", "measure", "integer", "Required posts."),
            ("sanctioned_posts", "measure", "integer", "Sanctioned posts."),
            ("filled_posts", "measure", "integer", "Filled posts."),
            ("staff_actually_available", "measure", "integer", "Actually available staff."),
            ("staff_sufficiency_percentage", "measure", "real", "Actually available divided by required posts."),
            ("vacancy_percentage", "measure", "real", "Vacant divided by sanctioned posts."),
            ("contract_staff_count", "measure", "integer", "Contract staff count."),
            ("salary_cost", "measure", "real", "Salary cost in rupees."),
            ("contract_staff_cost", "measure", "real", "Contract staff cost in rupees."),
            ("overtime_cost", "measure", "real", "Overtime cost in rupees."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_service_monthly",
        "Facility-service-demographic-month capacity, demand, delivery, access, and unmet-need view.",
        "Facility x ServiceCategory x DemographicGroup x Month",
        (
            ("facility_id", "entity_key", "integer", "Stable facility key."),
            ("facility_name", "label", "text", "Facility display name."),
            ("district_name", "dimension", "text", "Administrative district."),
            ("service_category", "dimension", "text", "Service category."),
            ("demographic_group", "dimension", "text", "Aggregate equity group."),
            ("month_id", "time", "text", "Reporting month."),
            ("service_capacity", "measure", "integer", "Service capacity."),
            ("service_demand", "measure", "integer", "Estimated service demand."),
            ("services_delivered", "measure", "integer", "Services delivered."),
            ("service_utilisation_percentage", "measure", "real", "Delivered divided by capacity."),
            ("estimated_unmet_demand", "measure", "integer", "Estimated unmet demand."),
            ("referrals_out", "measure", "integer", "Referrals out."),
            ("average_waiting_days", "measure", "real", "Average waiting days."),
            ("service_availability_status", "status", "text", "Availability state."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_budget_monthly",
        "Organisation-or-facility budget-head-month funding, expenditure, liability, and delay view.",
        "Organisation or Facility x BudgetHead x Month",
        (
            ("organisation_id", "entity_key", "integer", "Stable organisation key."),
            ("organisation_name", "label", "text", "Organisation name."),
            ("facility_id", "foreign_key", "integer", "Optional facility key."),
            ("facility_name", "label", "text", "Optional facility name."),
            ("budget_head_name", "dimension", "text", "Budget head."),
            ("month_id", "time", "text", "Reporting month."),
            ("revised_budget", "measure", "real", "Revised budget in rupees."),
            ("funds_released", "measure", "real", "Funds released in rupees."),
            ("funds_available", "measure", "real", "Funds available in rupees."),
            ("committed_expenditure", "measure", "real", "Committed expenditure."),
            ("actual_expenditure", "measure", "real", "Actual expenditure."),
            ("unpaid_liabilities", "measure", "real", "Unpaid liabilities."),
            ("budget_utilisation_percentage", "measure", "real", "Actual expenditure divided by available funds."),
            ("release_delay_days", "measure", "real", "Release delay in days."),
            ("payment_delay_days", "measure", "real", "Payment delay in days."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_programme_monthly",
        "Programme-district-demographic-month coverage, cost, activity, and outcome view.",
        "Programme x District x DemographicGroup x Month",
        (
            ("programme_id", "entity_key", "integer", "Stable programme key."),
            ("programme_name", "label", "text", "Programme name."),
            ("district_name", "dimension", "text", "Target district."),
            ("demographic_group", "dimension", "text", "Aggregate equity group."),
            ("month_id", "time", "text", "Reporting month."),
            ("target_population", "measure", "integer", "Target population."),
            ("eligible_population", "measure", "integer", "Eligible population."),
            ("population_reached", "measure", "integer", "Population reached."),
            ("coverage_percentage", "measure", "real", "Reached divided by eligible population."),
            ("programme_budget", "measure", "real", "Programme budget."),
            ("programme_expenditure", "measure", "real", "Programme expenditure."),
            ("cost_per_person_reached", "measure", "real", "Expenditure divided by population reached."),
            ("outcome_indicator_value", "measure", "real", "Registered outcome value."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_scheme_monthly",
        "Scheme-district-demographic-month enrolment, claims, payment, and fraud-signal view.",
        "Scheme x District x DemographicGroup x Month",
        (
            ("scheme_id", "entity_key", "integer", "Stable scheme key."),
            ("scheme_name", "label", "text", "Scheme name."),
            ("district_name", "dimension", "text", "District."),
            ("demographic_group", "dimension", "text", "Aggregate equity group."),
            ("month_id", "time", "text", "Reporting month."),
            ("eligible_individuals", "measure", "integer", "Eligible individuals."),
            ("enrolled_individuals", "measure", "integer", "Enrolled individuals."),
            ("beneficiaries_served", "measure", "integer", "Beneficiaries served."),
            ("coverage_percentage", "measure", "real", "Enrolled divided by eligible individuals."),
            ("claims_submitted", "measure", "integer", "Claims submitted."),
            ("claims_approved", "measure", "integer", "Claims approved."),
            ("claims_rejected", "measure", "integer", "Claims rejected."),
            ("claim_approval_percentage", "measure", "real", "Approved divided by submitted claims."),
            ("claim_amount_paid", "measure", "real", "Claim amount paid."),
            ("average_claim_processing_days", "measure", "real", "Average processing days."),
            ("fraud_signal_count", "measure", "integer", "Fraud signals requiring review."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
    _dataset(
        "analytics_health_data_quality_monthly",
        "Source-system-organisation-month completeness, validity, freshness, and quality score view.",
        "SourceSystem x Organisation x Month",
        (
            ("source_code", "identifier", "text", "Source system code."),
            ("source_name", "label", "text", "Source system name."),
            ("organisation_name", "dimension", "text", "Submitting organisation."),
            ("month_id", "time", "text", "Reporting month."),
            ("records_expected", "measure", "integer", "Expected records."),
            ("records_received", "measure", "integer", "Received records."),
            ("records_valid", "measure", "integer", "Valid records."),
            ("records_rejected", "measure", "integer", "Rejected records."),
            ("data_freshness_days", "assurance", "real", "Data age in days."),
            ("overall_data_quality_score", "assurance", "real", "Governed quality score from zero to 100."),
            ("source_version", "provenance", "text", "Source dataset version."),
        ),
    ),
)


MINISTRY_METRICS = (
    {"name": "monthly_outpatient_visits", "dataset_name": "analytics_health_facility_monthly", "expression": "SUM(outpatient_visits)", "aggregation": "sum", "unit": "visit_count", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Monthly outpatient visits."},
    {"name": "bed_occupancy_percentage", "dataset_name": "analytics_health_facility_monthly", "expression": "AVG(bed_occupancy_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Average facility bed occupancy; aggregate recomputation should use bed-days when available."},
    {"name": "medicine_sufficiency_percentage", "dataset_name": "analytics_health_medicine_monthly", "expression": "AVG(medicine_sufficiency_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Available medicine stock value divided by estimated required stock value."},
    {"name": "critical_stockout_incidents", "dataset_name": "analytics_health_medicine_monthly", "expression": "SUM(critical_stockout_incidents)", "aggregation": "sum", "unit": "incident_count", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Critical medicine stockout incidents."},
    {"name": "equipment_functionality_percentage", "dataset_name": "analytics_health_equipment_monthly", "expression": "AVG(equipment_functionality_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Functional equipment divided by available equipment."},
    {"name": "monthly_equipment_downtime", "dataset_name": "analytics_health_equipment_monthly", "expression": "SUM(total_downtime_hours)", "aggregation": "sum", "unit": "hours", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Equipment downtime by month."},
    {"name": "staffing_sufficiency_percentage", "dataset_name": "analytics_health_staffing_monthly", "expression": "AVG(staff_sufficiency_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Actually available staff divided by required posts."},
    {"name": "estimated_unmet_service_demand", "dataset_name": "analytics_health_service_monthly", "expression": "SUM(estimated_unmet_demand)", "aggregation": "sum", "unit": "service_count", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Estimated unmet service demand."},
    {"name": "monthly_budget_utilisation_percentage", "dataset_name": "analytics_health_budget_monthly", "expression": "AVG(budget_utilisation_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "facility_id", "time_field": "month_id", "valid_transforms": "none", "description": "Actual expenditure divided by available funds."},
    {"name": "programme_coverage_percentage", "dataset_name": "analytics_health_programme_monthly", "expression": "AVG(coverage_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "programme_id", "time_field": "month_id", "valid_transforms": "none", "description": "Population reached divided by eligible population."},
    {"name": "scheme_coverage_percentage", "dataset_name": "analytics_health_scheme_monthly", "expression": "AVG(coverage_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "scheme_id", "time_field": "month_id", "valid_transforms": "none", "description": "Enrolled individuals divided by eligible individuals."},
    {"name": "claim_approval_percentage", "dataset_name": "analytics_health_scheme_monthly", "expression": "AVG(claim_approval_percentage)", "aggregation": "avg", "unit": "percent", "entity_key": "scheme_id", "time_field": "month_id", "valid_transforms": "none", "description": "Approved claims divided by submitted claims."},
    {"name": "ministry_data_quality_score", "dataset_name": "analytics_health_data_quality_monthly", "expression": "AVG(overall_data_quality_score)", "aggregation": "avg", "unit": "score_0_100", "time_field": "month_id", "valid_transforms": "none", "description": "Average governed data-quality score."},
)


MINISTRY_RELATIONSHIPS = (
    {"from_entity": "Department", "predicate": "oversees", "to_entity": "Directorate", "join_expression": "master_organisation.parent_organisation_id = parent.organisation_id", "description": "A department oversees its directorates."},
    {"from_entity": "Directorate", "predicate": "controls", "to_entity": "Organisation", "join_expression": "master_organisation.parent_organisation_id = directorate.organisation_id", "description": "A directorate controls or supervises subordinate organisations."},
    {"from_entity": "Organisation", "predicate": "operates", "to_entity": "Facility", "join_expression": "master_facility.parent_organisation_id = master_organisation.organisation_id", "description": "Administrative operation or responsibility for a facility."},
    {"from_entity": "Hospital", "predicate": "is_a", "to_entity": "Facility", "join_expression": "hospital identity maps to master_facility", "description": "Legacy hospital identities are a subset of the common facility model."},
    {"from_entity": "Facility", "predicate": "has_type", "to_entity": "FacilityType", "join_expression": "master_facility.facility_type_id = master_facility_type.facility_type_id", "description": "Governed facility classification."},
    {"from_entity": "Facility", "predicate": "located_in", "to_entity": "District", "join_expression": "master_facility.district_id = master_geographic_area.geographic_area_id", "description": "Administrative district location."},
    {"from_entity": "Facility", "predicate": "located_in", "to_entity": "LocalBody", "join_expression": "master_facility.local_body_id = master_geographic_area.geographic_area_id", "description": "Local-body location."},
    {"from_entity": "Facility", "predicate": "uses_system_of_medicine", "to_entity": "SystemOfMedicine", "join_expression": "master_facility.system_of_medicine_id = master_system_of_medicine.system_of_medicine_id", "description": "System of medicine practised by the facility."},
    {"from_entity": "Facility", "predicate": "offers", "to_entity": "ServiceCategory", "join_expression": "analytics_service_monthly.facility_id and service_category_id", "description": "Observed facility service offering."},
    {"from_entity": "Facility", "predicate": "requires", "to_entity": "StaffCategory", "join_expression": "analytics_staffing_monthly.facility_id and staff_category_id", "description": "Required workforce category."},
    {"from_entity": "Facility", "predicate": "requires", "to_entity": "EquipmentCategory", "join_expression": "analytics_equipment_monthly.facility_id and equipment_category_id", "description": "Required equipment category."},
    {"from_entity": "Facility", "predicate": "depends_on", "to_entity": "InfrastructureCategory", "join_expression": "analytics_infrastructure_monthly.facility_id and infrastructure_category_id", "description": "Supporting infrastructure dependency."},
    {"from_entity": "Facility", "predicate": "refers_to", "to_entity": "Facility", "join_expression": "analytics_referral_flow_monthly.source_facility_id = source and destination_facility_id = destination", "description": "Observed aggregate referral flow."},
    {"from_entity": "Organisation", "predicate": "administers", "to_entity": "Programme", "join_expression": "master_programme.administering_organisation_id = master_organisation.organisation_id", "description": "Programme administration."},
    {"from_entity": "Organisation", "predicate": "administers", "to_entity": "Scheme", "join_expression": "master_scheme.administering_organisation_id = master_organisation.organisation_id", "description": "Scheme administration."},
    {"from_entity": "Programme", "predicate": "targets", "to_entity": "District", "join_expression": "analytics_programme_monthly.programme_id and district_id", "description": "Programme target geography."},
    {"from_entity": "Programme", "predicate": "targets", "to_entity": "DemographicGroup", "join_expression": "analytics_programme_monthly.demographic_group_id", "description": "Aggregate programme equity dimension."},
    {"from_entity": "Facility", "predicate": "funded_by", "to_entity": "BudgetHead", "join_expression": "finance_budget_monthly.facility_id and budget_head_id", "description": "Facility funding classification."},
    {"from_entity": "Facility", "predicate": "spends_on", "to_entity": "CostCategory", "join_expression": "finance_expenditure_monthly.facility_id and cost_category_id", "description": "Facility expenditure classification."},
    {"from_entity": "Supplier", "predicate": "supplies", "to_entity": "ProcurementCategory", "join_expression": "analytics_supplier_performance_monthly.supplier_id and procurement_category_id", "description": "Observed supply category."},
    {"from_entity": "Supplier", "predicate": "contracted_by", "to_entity": "Organisation", "join_expression": "analytics_procurement_monthly.supplier_id and procuring_organisation_id", "description": "Observed contracting organisation."},
    {"from_entity": "Project", "predicate": "improves", "to_entity": "Facility", "join_expression": "master_project.facility_id = master_facility.facility_id", "description": "Facility improved by a project."},
    {"from_entity": "Project", "predicate": "funded_by", "to_entity": "BudgetHead", "join_expression": "master_project.budget_head_id = master_budget_head.budget_head_id", "description": "Project budget source."},
    {"from_entity": "AnalyticalMetric", "predicate": "measures", "to_entity": "Facility", "join_expression": "semantic_metric_definition.dataset_name references a facility-grain view", "description": "Facility-level registered metric."},
    {"from_entity": "AnalyticalCapability", "predicate": "uses_metric", "to_entity": "AnalyticalMetric", "join_expression": "semantic_capability_input input_type = METRIC", "description": "Approved metric input to a governed capability."},
    {"from_entity": "SourceSystem", "predicate": "supplies_data_for", "to_entity": "AnalyticalCapability", "join_expression": "fact source_system_id plus semantic capability inputs", "description": "Lineage from operational source to analytical capability."},
)


MINISTRY_ALIASES = (
    {"term": "facility", "target_type": "entity", "target_name": "Facility"},
    {"term": "facilities", "target_type": "entity", "target_name": "Facility"},
    {"term": "organisation", "target_type": "entity", "target_name": "Organisation"},
    {"term": "directorate", "target_type": "entity", "target_name": "Directorate"},
    {"term": "programme", "target_type": "entity", "target_name": "Programme"},
    {"term": "scheme", "target_type": "entity", "target_name": "Scheme"},
    {"term": "supplier", "target_type": "entity", "target_name": "Supplier"},
    {"term": "medicine sufficiency", "target_type": "metric", "target_name": "medicine_sufficiency_percentage"},
    {"term": "medicine shortage", "target_type": "metric", "target_name": "medicine_sufficiency_percentage"},
    {"term": "stockout", "target_type": "metric", "target_name": "critical_stockout_incidents"},
    {"term": "equipment functionality", "target_type": "metric", "target_name": "equipment_functionality_percentage"},
    {"term": "staff sufficiency", "target_type": "metric", "target_name": "staffing_sufficiency_percentage"},
    {"term": "staffing gap", "target_type": "metric", "target_name": "staffing_sufficiency_percentage"},
    {"term": "budget utilisation", "target_type": "metric", "target_name": "monthly_budget_utilisation_percentage"},
    {"term": "programme coverage", "target_type": "metric", "target_name": "programme_coverage_percentage"},
    {"term": "scheme coverage", "target_type": "metric", "target_name": "scheme_coverage_percentage"},
    {"term": "claim approval", "target_type": "metric", "target_name": "claim_approval_percentage"},
    {"term": "data quality", "target_type": "metric", "target_name": "ministry_data_quality_score"},
    {"term": "equity", "target_type": "entity", "target_name": "DemographicGroup"},
)


MINISTRY_DATASET_LINKS = (
    {"dataset_name": "analytics_health_facility_monthly", "entity_name": "Facility", "metric_name": "monthly_outpatient_visits"},
    {"dataset_name": "analytics_health_facility_monthly", "entity_name": "Facility", "metric_name": "bed_occupancy_percentage"},
    {"dataset_name": "analytics_health_medicine_monthly", "entity_name": "Facility", "metric_name": "medicine_sufficiency_percentage"},
    {"dataset_name": "analytics_health_medicine_monthly", "entity_name": "Facility", "metric_name": "critical_stockout_incidents"},
    {"dataset_name": "analytics_health_equipment_monthly", "entity_name": "EquipmentCategory", "metric_name": "equipment_functionality_percentage"},
    {"dataset_name": "analytics_health_equipment_monthly", "entity_name": "Facility", "metric_name": "monthly_equipment_downtime"},
    {"dataset_name": "analytics_health_staffing_monthly", "entity_name": "StaffCategory", "metric_name": "staffing_sufficiency_percentage"},
    {"dataset_name": "analytics_health_service_monthly", "entity_name": "ServiceCategory", "metric_name": "estimated_unmet_service_demand"},
    {"dataset_name": "analytics_health_budget_monthly", "entity_name": "BudgetHead", "metric_name": "monthly_budget_utilisation_percentage"},
    {"dataset_name": "analytics_health_programme_monthly", "entity_name": "Programme", "metric_name": "programme_coverage_percentage"},
    {"dataset_name": "analytics_health_scheme_monthly", "entity_name": "Scheme", "metric_name": "scheme_coverage_percentage"},
    {"dataset_name": "analytics_health_scheme_monthly", "entity_name": "Scheme", "metric_name": "claim_approval_percentage"},
    {"dataset_name": "analytics_health_data_quality_monthly", "entity_name": "SourceSystem", "metric_name": "ministry_data_quality_score"},
)


MINISTRY_DATASET_JOINS = (
    {
        "left_dataset": "analytics_health_facility_monthly",
        "right_dataset": "analytics_health_medicine_monthly",
        "keys": (("facility_id", "facility_id"), ("month_id", "month_id")),
        "cardinality": "one_to_one_at_facility_month",
        "description": "Join facility activity and aggregate medicine status at Facility x Month grain.",
    },
    {
        "left_dataset": "analytics_health_facility_monthly",
        "right_dataset": "analytics_health_equipment_monthly",
        "keys": (("facility_id", "facility_id"), ("month_id", "month_id")),
        "cardinality": "one_to_many_by_equipment_category",
        "description": "Join only when equipment category remains visible or is aggregated before the join.",
    },
    {
        "left_dataset": "analytics_health_facility_monthly",
        "right_dataset": "analytics_health_staffing_monthly",
        "keys": (("facility_id", "facility_id"), ("month_id", "month_id")),
        "cardinality": "one_to_many_by_staff_category",
        "description": "Join only when staff category remains visible or is aggregated before the join.",
    },
    {
        "left_dataset": "analytics_health_facility_monthly",
        "right_dataset": "analytics_health_budget_monthly",
        "keys": (("facility_id", "facility_id"), ("month_id", "month_id")),
        "cardinality": "one_to_many_by_budget_head",
        "description": "Join only when budget head remains visible or is aggregated before the join.",
    },
)

